version: 2
jobs:
  build:
    docker:
      - image: node:8-wheezy
    working_directory: /usr/src/app
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Commitlint
          name: npx commitlint --from origin/master --to HEAD
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Release
          command: npm run semantic-release
      - store_artifacts:
          path: /usr/src/app/coverage
