version: 2.1
jobs:
  build:
    docker:
      - image: node:8-wheezy
    steps:
      - checkout
      - run: npm install
      - run: npx commitlint --from origin/master --to HEAD
      - run: npm test
      - store_artifacts:
          path: coverage
  release:
    docker:
      - image: node:8-wheezy
    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release
workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          context: deploy
          requires:
            - build
          filters:
            branches:
              only: semantic-release
