version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx commitlint --from origin/master --to HEAD
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - store_artifacts:
          path: coverage
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - attach_workspace:
          at: .
      - run: npm run semantic-release
workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          context: deploy
          requires:
            - build
          filters:
            branches:
              only: master
